AWSTemplateFormatVersion: "2010-09-09"

Description: "event-bus-source--send-event-to-target-account.yaml"

Parameters:

  AppName:
    Description: "App name."
    Type: "String"
    Default: "gov-base"

  TargetAwsAccountId:
    Description: "target aws account id."
    Type: "String"

  NotificationEventPatternSourceList:
    Description: "comma delimited notification event source list."
    Type: "CommaDelimitedList"
    Default: ""

Resources: 

  ### ローカルのイベントをターゲットのイベントバスに送信するためのロール

  SendNotificationEventToTargetAccountEventBusRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AppName}---send-notification-event-to-target-account-event-bus"
      Path: !Sub "/${AppName}/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "events.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/${AppName}---permissions-boundary-for-role"

  # 上のロールのStatementに含めるとエラーになるので外出しのPolicyにした。
  # https://qiita.com/sot528/items/2263fab0dbb55d6ce032
  SendNotificationEventToTargetAccountEventBusPolicyExceptAssumeRole:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AppName}---send-notification-event-to-target-account-event-bus-policy-except-assume-role"
      Roles:
        - !Ref SendNotificationEventToTargetAccountEventBusRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "events:PutEvents"
            Resource: 
              - !Sub "arn:aws:events:${AWS::Region}:${TargetAwsAccountId}:event-bus/default"


  ### ローカルのイベントをターゲットのイベントバスに送信するためのルール
  # "aws.securityhub" で統合されるサービス一覧
  # https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-internal-providers.html#internal-integrations-summary

  SendNotificationEventToTargetAccountEventBus:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AppName}---send-notification-event-to-target-account-event-bus"
      EventBusName: "default"
      State: "ENABLED"
      RoleArn: !GetAtt SendNotificationEventToTargetAccountEventBusRole.Arn
      EventPattern:
        source: !Ref NotificationEventPatternSourceList
      # EventPattern: |
      #   {
      #     "source": [
      #       "aws.securityhub","aws.devops-guru"
      #     ]
      #   }
      Targets:
        - Arn: !Sub "arn:aws:events:${AWS::Region}:${TargetAwsAccountId}:event-bus/default"
          Id: !Sub "${AppName}---target-account-event-bus"
