AWSTemplateFormatVersion: "2010-09-09"

Description: "switch-role-target-role-for-jump.yaml"

Parameters:

  AppName:
    Description: "App name."
    Type: "String"
    Default: "gov-base"

  JumpAwsAccountId:
    AllowedPattern: "^[0-9]*$"
    Type: "String"
    Description: "Jump AWS Account ID"

Resources:

  ### 読み取り権限ロール
  ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      Path: "/"
      RoleName: !Sub "${AppName}---switch-role-target--read-only"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      MaxSessionDuration: 43200
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${JumpAwsAccountId}:root"
            Action:
              - "sts:AssumeRole"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": true
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/${AppName}---permissions-boundary-for-role"
