AWSTemplateFormatVersion: "2010-09-09"

Description: "event-bus-target.yaml"

Parameters:

  AppName:
    Description: "App name."
    Type: "String"
    Default: "gov-base"
  
  SourceAwsAccountIds:
    Description: "comma delimited source aws account id list."
    Type: "CommaDelimitedList"
    Default: ""

  
Resources: 

  EventBusPolicy:
    Type: AWS::Events::EventBusPolicy
    Properties:
      EventBusName: default
      StatementId: !Sub "${AppName}---put-events-from-source-event-bus"
      Statement:
        Sid: !Sub "${AppName}---put-events-from-source-event-bus"
        Effect: "Allow"
        Principal: 
          AWS: !Ref SourceAwsAccountIds
        Action: "events:PutEvents"
        Resource : !Sub "arn:aws:events:${AWS::Region}:${AWS::AccountId}:event-bus/default"
