AWSTemplateFormatVersion: "2010-09-09"

Description: "iam-access-analyzer.yaml"

Parameters:

  AppName:
    Description: "App name."
    Type: "String"
    Default: "gov-base"

Resources:

  Analyzer:
    Type: AWS::AccessAnalyzer::Analyzer
    Properties:
      AnalyzerName: !Sub "${AppName}---analyzer"
      Type: "ACCOUNT"
