AWSTemplateFormatVersion: "2010-09-09"

Description: "cfn-assets-storage.yaml"

Parameters:

  AppName:
    Description: "App name."
    Type: "String"
    Default: "gov-base"

Resources:

  CfnAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}---cfn-assets---${AWS::Region}-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"
      VersioningConfiguration:
        Status: "Enabled"
